### ISSUE TITLE
Server Error (500) with certain searches

### ISSUE THREAD

**Issue by camduval** [UAlbertaALTLab/wordnet-docker#1]
I am getting 'Server Error (500)' show up on the screen, but for some reason only when looking up lemmas for clean i.e. 'clean', 'cleaning', 'cleaned'. Not sure if it is just with that word set or if there are more like this.

**Comment by fbanados** [comment]
aha!  Dots are valid in entries, so the command I was doing to change formats was incorrect.  I will fix that, push to production and close this issue when I'm done.

**Comment by fbanados** [comment]
e.g. "g.i." is a valid entry in Wordnet.

**Comment by fbanados** [comment]
Deployed.  Should be fixed!  If there are other problems please open a new issue. Thanks!
